# -*- coding: utf-8 -*-
"""score_average.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XP3HSy8Vj4VjdnEoKJ__r3d73sfgmSD8
"""

score=input().split()

countF=0
average=0
for i in score:
  if int(i)<60:
    countF+=1
    average+=int(i)
    average=average/len(score)
print(countF)
print(average)



